In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/test-file/tested.csv


In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator, SimpleImputer

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [4]:
df = pd.read_csv('/kaggle/input/test-file/tested.csv', usecols=['Age', 'Fare','Survived'])

In [5]:
df.head()

Survived   Age     Fare
0         0  34.5   7.8292
1         1  47.0   7.0000
2         0  62.0   9.6875
3         0  27.0   8.6625
4         1  22.0  12.2875

In [6]:
df.isnull().mean()*100

Survived     0.000000
Age         20.574163
Fare         0.239234
dtype: float64

In [7]:
df.dropna(subset=['Fare'] ,inplace =True)

In [8]:
df.isnull().mean()*100

Survived     0.000000
Age         20.623501
Fare         0.000000
dtype: float64

In [9]:
X = df.drop(columns =['Survived'])
y = df['Survived']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size =0.2, random_state= 42)

In [11]:
X_train.head()

Age     Fare
287  24.0  82.2667
387  57.0  13.0000
210  32.0  22.5250
93    NaN   8.0500
285  36.0   7.2500

In [12]:
# without using missing indicator, replacing missing values by mean

si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [13]:
X_train_trf

array([[ 24.        ,  82.2667    ],
       [ 57.        ,  13.        ],
       [ 32.        ,  22.525     ],
       [ 30.08234615,   8.05      ],
       [ 36.        ,   7.25      ],
       [ 29.        , 221.7792    ],
       [ 14.        ,   9.225     ],
       [ 25.        ,   7.925     ],
       [ 30.08234615,   6.4375    ],
       [ 30.        ,  15.55      ],
       [  1.        ,  12.1833    ],
       [ 35.        ,  12.35      ],
       [ 18.        ,  60.        ],
       [ 25.        ,  10.5       ],
       [ 32.        ,   7.775     ],
       [ 27.        ,   8.6625    ],
       [ 27.        ,   7.925     ],
       [ 30.08234615,   7.05      ],
       [ 17.        ,   7.8958    ],
       [ 18.        ,   7.775     ],
       [ 30.08234615,   7.75      ],
       [ 22.        ,   7.725     ],
       [ 27.        ,   8.6625    ],
       [ 29.        ,  22.025     ],
       [ 30.        , 164.8667    ],
       [ 30.08234615,  25.4667    ],
       [ 33.        ,   7.8542    ],
 

In [14]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf, y_train)

y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6428571428571429

In [15]:
mi = MissingIndicator()

mi.fit(X_train)

MissingIndicator()

In [16]:
mi.features_

array([0])

In [17]:
X_train_missing = mi.transform(X_train)

In [18]:
X_train_missing

array([[False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [

In [19]:
X_test_missing = mi.transform(X_test)

In [20]:
X_train['Age_NA'] = X_train_missing

In [21]:
X_test['Age_NA'] = X_test_missing

In [22]:
X_train

Age     Fare  Age_NA
287  24.0  82.2667   False
387  57.0  13.0000   False
210  32.0  22.5250   False
93    NaN   8.0500    True
285  36.0   7.2500   False
..    ...      ...     ...
71   21.0   7.8958   False
106  21.0   7.8208   False
271   NaN   7.7500    True
349  31.0  21.0000   False
102   NaN   7.7500    True

[333 rows x 3 columns]

In [23]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [28]:
y_pred.size

333

In [29]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2, y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)


0.6428571428571429

# **Misisng indicator can be applied directly using Simple Imputer itself.**

In [30]:
si = SimpleImputer(add_indicator = True)
# using this add indicator, we can add indicator column directly using missing indicator class

In [31]:
X_train = si.fit_transform(X_train)

In [32]:
X_test = si.transform(X_test)

In [33]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2, y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)


0.6428571428571429