In [1]:
import numpy as np
import pandas as pd


In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.read_csv('/content/covid_toy.csv')

In [5]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df['cough'].value_counts()

Mild      62
Strong    38
Name: cough, dtype: int64

In [7]:
df['city'].value_counts()

Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size = 0.2)


In [13]:
X_train

age  gender  fever   cough       city
30   15    Male  101.0    Mild      Delhi
17   40  Female   98.0  Strong      Delhi
26   19  Female  100.0    Mild    Kolkata
76   80    Male  100.0    Mild  Bangalore
43   22  Female   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
15   70    Male  103.0  Strong    Kolkata
21   73    Male   98.0    Mild  Bangalore
95   12  Female  104.0    Mild  Bangalore
82   24    Male   98.0    Mild    Kolkata
99   10  Female   98.0  Strong    Kolkata

[80 rows x 5 columns]

# **Without using Column transformer**

In [15]:
# adding simple imputer to fever column, to fill in the missing values.
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape
# using SI, all the missing values of the data has been replaced with the mean value of the data.

(80, 1)

In [16]:
# Ordinal encoding for the cough column

oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [17]:
# OneHot Encoding for gender and city column

ohe = OneHotEncoder(drop = 'first', sparse = False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],


In [18]:
# now we have to concatenate all, but before that extract age col

X_train_age = X_train.drop(columns = ['gender','fever','cough','city']).values

X_test_age = X_test.drop(columns =['gender','fever','cough','city']).values

X_train_age



array([[15],
       [40],
       [19],
       [80],
       [22],
       [14],
       [23],
       [42],
       [65],
       [64],
       [75],
       [51],
       [83],
       [14],
       [55],
       [60],
       [42],
       [11],
       [68],
       [27],
       [73],
       [65],
       [38],
       [16],
       [79],
       [69],
       [80],
       [19],
       [56],
       [65],
       [49],
       [81],
       [49],
       [74],
       [27],
       [81],
       [82],
       [72],
       [66],
       [71],
       [83],
       [64],
       [65],
       [71],
       [34],
       [20],
       [13],
       [12],
       [42],
       [ 5],
       [25],
       [59],
       [17],
       [34],
       [34],
       [51],
       [48],
       [33],
       [11],
       [47],
       [20],
       [18],
       [31],
       [16],
       [54],
       [84],
       [19],
       [34],
       [20],
       [50],
       [69],
       [ 8],
       [19],
       [24],
       [46],
       [70],
       [73],

In [20]:
# now concatenating all

X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city,X_train_cough), axis=1)

X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis =1)

X_train_transformed.shape

(80, 7)

# **Now doing the same process using Column Transformer**

In [21]:
from sklearn.compose import ColumnTransformer

In [25]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories = [['Mild','Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse = False, drop='first'),['gender','city'])
], remainder='passthrough')

In [26]:
transformer.fit_transform(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  15.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  40.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [100.70833333,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [27]:
transformer.fit_transform(X_train).shape

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 7)

In [28]:
transformer.fit_transform(X_test).shape

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(20, 7)